# Generated by Django 3.2.8 on 2021-11-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('initDate', models.DateField()),
                ('finalDate', models.DateField()),
            ],
        ),
    ]
